import 'firebun/server/init'
import * as functions from 'firebase-functions'
import template from '#app/template'

export const hello = functions.https.onRequest((_request, response) => {
  response.send(`Hello, world! Generated by Node.js ${process.version}`)
})

export const renderer = functions.https.onRequest((_request, response) => {
  response.send(template())
})
